services:
  db_geocode_reverse:
    container_name: db_geocode
    image: postgis/postgis
    volumes:
      - pgdata:/var/lib/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  geocode_reverse_api:
    container_name: geocode_api
    image: geocode_reverse_api
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - "8080:8080"
    depends_on:
      db_geocode_reverse:
        condition: service_healthy


volumes:
  pgdata:
