services:
  db_geocode_reverse:
    image: postgis/postgis
    volumes:
      - pgdata:/var/lib/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10

  geocode_reverse_api:
    image: geocode_reverse_api
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8080:8080"
    depends_on: 
      - db_geocode_reverse
    environment:
      DB_HOST: postgresql+psycopg://postgres:604dcae21fbcddd83afd@db_geocode_reverse/wrap_geocode_reverse"
        
volumes:
  pgdata:
