name: Pipelline Teste
on: 
  push: 
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-verion: '3.12'
